name: Build bootc image

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  schedule:
    - cron: "0 0 * * sun"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

env:
  IMAGE_DESC: "Generated Fedora atomic image using github.com/wstobb/fedora-custom-bootc-template"
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "latest"
  IS_MAIN_PUSH: ${{ github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Prepare environment
        run: |
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}
          echo "IMAGE_TAG=$(date +%Y%m%d)" >> ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Cosign
        if: env.IS_MAIN_PUSH == 'true'
        uses: sigstore/cosign-installer@v3

      - name: Build with Podman
        run: |
          FULL_IMAGE="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"
          podman build \
            --format oci \
            --label "org.opencontainers.image.description=${{ env.IMAGE_DESC }}" \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            --tag ${FULL_IMAGE}:${{ env.DEFAULT_TAG }} \
            --tag ${FULL_IMAGE}:${{ env.IMAGE_TAG }} \
            --file ./Containerfile \
            .

      - name: Login to GHCR
        if: env.IS_MAIN_PUSH == 'true'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        if: env.IS_MAIN_PUSH == 'true'
        id: push
        run: |
          FULL_IMAGE="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"
          DIGEST=$(podman push ${FULL_IMAGE}:${{ env.DEFAULT_TAG }} --digestfile /tmp/digest.txt && cat /tmp/digest.txt)
          podman push ${FULL_IMAGE}:${{ env.IMAGE_TAG }}
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "image-ref=${FULL_IMAGE}@${DIGEST}" >> $GITHUB_OUTPUT

      - name: Sign image
        if: env.IS_MAIN_PUSH == 'true'
        run: |
          cosign sign --yes ${{ steps.push.outputs.image-ref }}